"""
Enhance BG Ch6-7-8 feedback to expert critique level
Ch6: 49% -> 90%+ (dhyana-yoga, mind control, unsuccessful yogi)
Ch7: 76% -> 90%+ (para/apara prakrti, jnana-vijnana, mahatma - refining existing)
Ch8: 80% -> 90%+ (ante kale, aksara, paths - refining existing)
"""
import json

def enhance_chapter(ch_num, enhancements):
    fname = f'data/quizzes/bg/{ch_num}-adult.json'
    with open(fname) as f:
        data = json.load(f)
    
    updated = 0
    for q in data['questions']:
        qid = q['id']
        if qid in enhancements:
            q['feedback'] = enhancements[qid]
            updated += 1
    
    with open(fname, 'w') as f:
        json.dump(data, f, indent=2)
    
    # Validate quality
    trap = sum(1 for q in data['questions'] if 'trap' in q.get('feedback','').lower())
    fp = sum(1 for q in data['questions'] if 'false path' in q.get('feedback','').lower())
    total = len(data['questions'])
    quality = ((trap + fp + total) / (total * 3)) * 100
    
    print(f"✅ Ch{ch_num} enhanced: {updated} questions updated, trap={trap}/{total}, fp={fp}/{total}, quality={quality:.0f}%")
    return quality

# === CHAPTER 6 ENHANCEMENTS === (All 25 questions - comprehensive coverage)
ch6_enhancements = {
    "bg6-q1": "Anashritah karma-phalam (unattached to work-fruits) karyam karma karoti (performs required work)-such person is sannyasi and yogi, not one who abandons agni (fire) and kriya (activities). The trap: external renunciation defines spiritual status. Why this matters: The false path is equating renunciation with inactivity-thinking abandoning duties makes one sannyasi, missing consciousness-quality determines status not behavior. Real understanding: True sannyasi/yogi performs full duties without fruit-attachment-internal detachment not external withdrawal. Fire-ceremony cessation doesn't make sannyasi; desireless work-performance does. Therefore cultivate internal renunciation while maintaining external engagement-transformation of consciousness not lifestyle defines authentic spiritual standing.",

    "bg6-q2": "What they call sannyasa (renunciation) know as yoga-na hyasannyasta-sankalpah yogi bhavati (one doesn't become yogi without renouncing sankalpas/desires). The trap: yoga and sannyasa are different paths. Why this matters: The false path is treating yoga-sannyasa as distinct alternatives-missing both require identical internal state: desire-renunciation. Real understanding: Yoga IS sannyasa when properly understood-both mean desire-transcendence enabling Krishna-consciousness. External differences (active vs withdrawn) less significant than internal similarity (desireless). This unifies seemingly divergent paths through consciousness-quality. Therefore don't artificially separate yoga-sannyasa-both achieve same internal state (desire-transcendence) through different external expressions, demonstrating consciousness-primacy over lifestyle-form.",

    "bg6-q3": "For muni (sage) desiring yoga-aroha (ascending), karma is karanam (means); for one yoga-arudha (ascended), shamah (tranquility) is karanam (means). The trap: single method for all stages. Why this matters: The false path is universal prescription-applying same practice regardless of advancement-level, missing graduated approach necessity. Real understanding: Yogaruruksu (beginner ascending) needs karma-yoga (engaged action) for purification; yogarudha (advanced ascended) needs shama (tranquility) for deepening. Different stages require different approaches-beginners purify through action, advanced stabilize through stillness. This validates developmental spirituality-meet practitioners where they are. Therefore apply stage-appropriate practice-karma-yoga for purification-phase, dhyana-yoga for realization-phase, recognizing spiritual path's progressive nature requiring different methods at different stages.",

    "bg6-q4": "When neither sarva-sankalpah (all desires) nor karmashu (in actions) attached-yogarudha (ascended in yoga) is declared. The trap: achievement through effort-cessation. Why this matters: The false path is thinking non-attachment means non-engagement-missing that desire-transcendence enables full action without binding attachment. Real understanding: Yogarudha simultaneously transcends desires AND actions' binding power-not by avoiding but by performing without attachment. Sankalpah (mental formations) and karmashu (activities) both transcended through consciousness-shift not behavior-modification. Therefore aim for engaged transcendence-active participation without volitional investment, achieving freedom through consciousness-quality not activity-quantity reduction.",

    "bg6-q5": "Uddharet atmana atmanam (one should elevate self by self)-atma (self) is both mitra (friend) and vairee (enemy) depending on self-mastery. The trap: external savior dependency. Why this matters: The false path is seeking external rescue-guru/God/circumstances to elevate while remaining passive, missing self-effort necessity. Real understanding: Self must elevate self through disciplined practice-no external agent can substitute for personal striving. Atma becomes friend (when controlled) or enemy (when uncontrolled)-same entity different relationship based on self-governance. This establishes personal responsibility-liberation requires active self-work not passive waiting for external salvation. Therefore engage in vigorous self-improvement-guru guides but individual must do work, God facilitates but won't override free will, taking personal responsibility for spiritual advancement.",

    "bg6-q6": "Self conquered for one who conquered self becomes mitra (friend); for unconquered, self acts as shatru-vat (like enemy) in enmity. The trap: self-acceptance without self-mastery. Why this matters: The false path is unconditional self-embrace-'love yourself as you are' without self-improvement, missing that uncontrolled self creates suffering. Real understanding: Conquered self (controlled through discipline) becomes ally enabling spiritual progress; unconquered self (following every impulse) sabotages spiritual goals like enemy. Not external enemy but internal lack of self-governance. Therefore practice self-control-not self-rejection but self-governance, converting inner chaos into inner ally through disciplined spiritual practice.",

    "bg6-q7": "Jitatmanah prashantasya (for self-conquered peaceful one)-same-sighted in sheeta-ushna (cold-heat), sukha-duhkha (pleasure-pain), mana-apamana (honor-dishonor). The trap: stoic emotional flattening. Why this matters: The false path is forced neutrality-suppressing all reactions mechanically, producing brittle equanimity requiring constant vigilance. Real understanding: Natural equanimity from self-conquest-jitatmanah (self-mastered) achieves prashantatva (peace) enabling sama-drishti (equal vision) toward all dualities. Not suppression but transcendence-dualities don't disturb because consciousness anchored beyond their reach. Therefore cultivate self-mastery producing natural peace-enables spontaneous equanimity without forced neutralization, achieving steadiness through spiritual grounding not psychological effort.",

    "bg6-q8": "Jnana-vijnana-trptatma (satisfied by knowledge-realization)-sees sama (equally) loshta-ashma-kanchana (clod-stone-gold). The trap: material value-nihilism. Why this matters: The false path is denying practical distinctions-treating gold and dirt as literally equivalent, missing transcendental vision that sees equal spiritual value beneath functional differences. Real understanding: Yuktatma (established yogi) sees sama not by ignoring differences but by transcending material value-hierarchy-clod/stone/gold differ functionally but equal spiritually as Krishna's energy. Not material leveling but spiritual transcendence. Therefore develop sama-drishti-recognize material varieties' practical utility while transcending attachment-hierarchy, seeing all as Krishna's energy regardless of material value-gradations.",

    "bg6-q9": "Suhrn-mitra-ari-udasina-madhyastha-dveshya-bandhu-sadhu-api-ca-papesu-sama-buddhih (equal-minded toward friend-enemy-neutral-mediator-hateful-relative-virtuous-sinful)-vishishyate (is distinguished). The trap: relationship-nihilism or naive universalism. Why this matters: The false path is either eliminating all distinctions (everyone equally significant) or maintaining distinctions that produce attachment-aversion, missing transcendental vision maintaining functional roles while transcending emotional reactions. Real understanding: Nine categories of relationships-friend/enemy/neutral/mediator/hateful/relative/virtuous/sinful-all met with sama-buddhi (equal intelligence) by yogi. Not ignoring differences but transcending reactive consciousness-honors functional distinctions (helping sadhu differs from managing papa) without internal turbulence. Therefore practice transcendent pragmatism-maintain appropriate responses to different persons while cultivating equal-minded consciousness underneath varied behaviors.",

    "bg6-q10": "Yogi constantly (satatam) should yunjita (engage) citta (consciousness) staying viviktadeshena (in solitary place), yatatma (self-controlled), nirasir (without desires), aparigraha (non-possessive). The trap: occasional practice sufficiency. Why this matters: The false path is part-time spirituality-meditating occasionally while remaining materially absorbed generally, missing consistent practice-requirement. Real understanding: Satatam (constantly) yunjita (should engage)-continuous practice not sporadic attempts. Ekaki (solitary) yatatma (self-controlled) nirasir (without desires) aparigraha (non-possessive)-comprehensive lifestyle supporting continuous practice. Not segmented spirituality (spiritual during meditation, material otherwise) but integrated consciousness. Therefore cultivate continuous practice-not just formal sessions but persistent consciousness-orientation toward Supreme throughout all activities, maintaining spiritual focus as life's constant backdrop.",

    "bg6-q11": "Shucau deshe (in clean place) establishing firm asana (seat)-neither ati-ucchritam (too high) nor ati-nicham (too low). The trap: location/equipment irrelevance or obsession. Why this matters: The false path is either neglecting practical conditions (practicing anywhere in any position) or obsessing over perfect setup (endless preparation without practice)-missing balanced attention to supportive conditions. Real understanding: Practical prerequisites-clean location, stable seat, moderate height-support meditation without guaranteeing it. Too much attention produces distraction through perfectionism; too little produces distraction through discomfort. Therefore establish reasonable practice-conditions-adequate cleanliness/stability/comfort enabling focus without obsessive environment-engineering, balancing external support with internal priority.",

    "bg6-q12": "Tatraikagram manah kritva (making mind one-pointed there)-controlling citta (consciousness) and indriyas (senses), practice yoga for atma-vishuddhaye (self-purification). The trap: meditation as relaxation technique. Why this matters: The false path is treating meditation as stress-relief-seeking pleasant feelings without transformation, missing purification-purpose. Real understanding: Ekagrata (one-pointedness) with controlled consciousness-senses for atma-vishuddhaye (self-purification)-meditation as spiritual discipline not therapeutic technique. Aim is consciousness-transformation (purifying false ego) not temporary stress-reduction. Therefore approach meditation as purification-practice-tolerating discomfort of confronting conditioned mind, seeking permanent transformation not temporary relief from material pressure.",

    "bg6-q13": "Samam kaya-shiro-grivam (body-head-neck evenly aligned) holding acalam (motionless)-practicing brahmacharya (celibacy) with citta (consciousness) on ekam (one) Krishna. The trap: physical posture suffices for meditation. Why this matters: The false path is postural perfection-assuming correct body-alignment produces meditation, missing consciousness-focus primacy. Real understanding: Physical alignment (samam upright posture, acalam stillness) supports but doesn't substitute for mental focus-citta fixed ekam (on one) Krishna. Brahmacharya (celibacy/sense-control) prevents distraction. Posture facilitates but consciousness determines meditation. Therefore maintain proper posture while prioritizing consciousness-discipline-body's stillness supports mind's one-pointedness but can't replace it, physical foundation enabling mental focus.",

    "bg6-q14": "Prashanta-atma (peaceful self) vigata-bhih (without fear) brahmachari-vrate sthitah (established in celibacy-vow)-controlling manas (mind), yukta (engaged) asita (should sit) mat-parah (Me as supreme goal). The trap: technique-fetishism divorced from devotion. Why this matters: The false path is mechanical meditation-perfecting technique without devotional consciousness, missing that Krishna as mat-parah (supreme goal) transforms practice from material to transcendental. Real understanding: Prerequisites-prashanta (peace), vigata-bhih (fearlessness), brahmacharya (celibacy), controlled mind-enable mat-parah (Me as supreme) meditation. Techniques serve devotional goal-meditation isn't impersonal mental training but Krishna-connection practice. Therefore infuse technique with devotion-don't separate meditation-mechanics from Krishna-focus, recognizing spiritual practice requires both proper method and devotional consciousness directing method toward Supreme Person.",

    "bg6-q15": "Yunjann evam (thus engaging) atmanam (self) yogi niyata-manah (controlled mind) shantim (peace) nirvana-paramam (supreme liberation) mat-samstha (abiding in Me) attains. The trap: liberation as cessation. Why this matters: The false path is negative nirvana-understanding liberation as extinction/nothingness, missing positive reality of mat-samstha (abiding in Krishna). Real understanding: Shanti (peace) and nirvana-parama (supreme liberation) defined as mat-samstha (abiding in Me)-not impersonal void but personal relationship with Supreme. Liberation isn't cessation but connection-ending material existence for transcendental existence with Krishna. Therefore seek positive liberation-not nothingness but Krishna-relationship, redefining freedom from absence-of-bondage to presence-of-devotion, transforming liberation from negative to positive concept.",

    "bg6-q16": "Na ati-ashnatas (not overeating) nor ati-svapnasya (oversleeping) yoga bhavati (becomes), nor ekantam (complete) anashnatah (fasting) nor jagratah (waking). The trap: extremism as spiritual authenticity. Why this matters: The false path is thinking austerity-intensity demonstrates spiritual seriousness-overfasting/undersleeping to prove dedication, missing balance requirement. Real understanding: Yoga requires yukta (balance) not ati (excess)-eating/sleeping/activity/rest all moderated. Neither over-indulgence (ati-ashnatas) nor over-restriction (ekantam anashnatas) supports practice. Extreme austerity appears impressive but undermines sustainability. Therefore practice moderate lifestyle-sufficient eating/sleeping enabling practice without excess/deficiency, recognizing spiritual life requires practical sustainability through balanced habits not impressive extremism producing burnout.",

    "bg6-q17": "Yuktahara-viharasya (balanced eating-recreation) yukta-ceshtasya (balanced activity) karma-su yukta-svapna-avabodhasya (balanced sleep-waking)-yoga becomes duhkha-ha (destroyer of suffering). The trap: spirituality requires lifestyle-deprivation. Why this matters: The false path is total material rejection-thinking spiritual advancement requires eliminating normal human needs, missing balance-principle enabling sustainable practice. Real understanding: Yukta (balanced) in all domains-eating/recreation/work/sleep-enables yoga destroying duhkha (suffering). Not ascetic deprivation but intelligent moderation-enjoying material necessities without excess. Sustainability through balance. Therefore maintain yukta-ahara-vihara-regulate material life intelligently supporting spiritual practice, avoiding both indulgent excess and ascetic deprivation, achieving sustainable spiritual lifestyle through moderation.",

    "bg6-q18": "When citta (consciousness) niruddham (controlled) sthitah (remains) atmani (in self) eva nispriha (without desires) from sarva-kamat (all material desires)-then yuktah (established) iti ucyate (is said). The trap: temporary meditation-success equals realization. Why this matters: The false path is mistaking meditative states for liberation-achieving temporary concentration and declaring victory, missing permanent transformation requirement. Real understanding: Yukta (established yogi) maintains consciousness sthita (steady) atmani (in self) nispriha (desireless) toward all kamat (desires)-not temporary concentration but stable realization. Occasional meditation-success differs from established transcendence. Therefore aim for stability-not impressive temporary states but consistent consciousness-quality persisting beyond formal practice, measuring progress by baseline consciousness-level not peak meditation-experiences.",

    "bg6-q19": "Yatha dipo nivata-sthah (as lamp in windless place) na ingate (doesn't flicker)-yoga-yukta (engaged yogi) whose citta (consciousness) controlled practicing atma-yoga (self-meditation). The trap: restless practice equals sincere effort. Why this matters: The false path is accepting meditation-turbulence as normal-mind wandering constantly yet continuing mechanically, missing that steadiness indicates actual progress. Real understanding: Controlled consciousness like lamp in windless place-steady unflickering focus. Metaphor indicates stability-quality not intensity-quantity. Restless struggling differs from steady focus-former indicates insufficient preparation, latter indicates ripening practice. Therefore cultivate steadiness-patient consistent practice developing natural stability, not frantic effort producing temporary concentration followed by collapse, measuring meditation-quality by steadiness not intensity.",

    "bg6-q20": "Where citta niruddham (consciousness controlled) yoga-sevatah (through yoga-practice)-where atmanam atmana pashyan (seeing self through self) atmani (in self) tushyati (is satisfied). The trap: external validation defines spiritual success. Why this matters: The false path is measuring advancement through others' recognition-seeking approval/status/reputation, missing self-validation from direct self-realization. Real understanding: Atmana pashyan atmanam (seeing self through self)-self validating through self-perception not external feedback. Atmani tushyati (satisfied in self)-fulfillment from inner realization not outer recognition. This internalization removes spiritual politics. Therefore cultivate self-validation-measure advancement through direct self-perception of consciousness-quality, not through external markers (titles/positions/followers), achieving independence from social validation even within spiritual community.",

    "bg6-q21": "Sukham atantikam (unlimited happiness) that buddhi-grahyam (intelligence grasps) atindriyam (beyond senses)-established knowing this na chalati (doesn't deviate) from tattvatah (from truth). The trap: sense-based happiness pursuit within spirituality. Why this matters: The false path is seeking pleasant sensory experiences through spiritual practice-sublime feelings/visions/experiences-remaining on indriya (sense) platform though religiously. Real understanding: Atindriyas sukham (transcendental happiness) buddhi-grahyam (grasped by purified intelligence)-beyond sense-perception. Atantikam (unlimited/permanent) versus indriya-sukham (sense-based pleasure) which is anta-vantam (limited/temporary). Established in this tattvatah (truth) na chalati (doesn't waver). Therefore transcend spiritual hedonism-seeking permanent transcendental realization not temporary sublime experiences, elevating spiritual aspiration beyond subtle sense-gratification to actual transcendence.",

    "bg6-q22": "Gaining which na aparam (no other) gain considers punyasam (greater)-established in which na duhkhena guruna api (not by heavy sorrow) vicalyate (is shaken). The trap: conditional spiritual commitment. Why this matters: The false path is commitment contingent on favorable circumstances-practicing when convenient, abandoning when difficult-missing unwavering establishment requirement. Real understanding: Having gained Krishna-connection considers it param labham (supreme gain)-nothing superior exists. Therefore na vicalyate (unshaken) guruna duhkhena api (even by heavy sorrow)-commitment persists through adversity. This unconditional dedication distinguishes authentic from superficial spirituality. Therefore develop unwavering commitment-establish Krishna-connection as non-negotiable life-priority maintained through favorable/unfavorable circumstances equally, testing spiritual maturity through adversity-persistence not prosperity-enthusiasm.",

    "bg6-q23": "Duhkha-samyoga-viyogam (severing sorrow-connection) yoga-samjnita (called yoga)-practice with nishcayena (determination) yoga without sannyasa vishada (abandoning sad-heartedness). The trap: spiritual passivity or emotionalism. Why this matters: The false path is either mechanical practice without conviction or emotion-driven inconsistency-both missing nishcayena (determined/decisive) requirement. Real understanding: Yoga defined as duhkha-samyoga-viyoga (disconnecting from suffering)-requires nishcayena (firm determination) without vishada (sad-heartedness/depression). Not grim determination but joyful resolve-enthusiasm without emotionalism. Therefore cultivate determined consistency-neither passive compliance nor emotional fluctuation, maintaining steady committed practice through clear conviction producing sustainable spiritual momentum.",

    "bg6-q24": "Sankalpa-prabhavan kaman (desires born from sankalpa-mental formations) tyaktva sarvan (abandoning all) asheshatah (completely)-restraining indriya-gramam (sense-group) manasa (by mind) from sarvatah (all sides). The trap: suppression without transformation. Why this matters: The false path is external control while desires persist-restraining behavior without addressing root sankalpa (mental formations), producing forced compliance not genuine transcendence. Real understanding: Address sankalpa-prabhavan (desire-source)-mental formations generating desires-not just controlling expressions. Tyaktva sarvan asheshtah (abandon completely without remainder)-thorough not superficial. Manasa (through mind) control indriya-gramam (sense-group)-mind-level work enabling sense-level control. Therefore work at root-level-transform sankalpa (mental formations) generating desires, not just restrain indriyas (senses) expressing desires, achieving genuine transformation not forced suppression.",

    "bg6-q25": "Shanai-shanai (gradually) uparamet (should cease) buddhi-dhrita-grihtaya (by intelligence held firmly)-fixing manas (mind) on atman (self) na kinchit api cintayet (should think nothing else). The trap: instant enlightenment expectation. Why this matters: The false path is expecting immediate transformation-demanding instant liberation producing frustration when progress is gradual, missing patience requirement. Real understanding: Shanai-shanai (gradually/slowly) approach-reasonable expectations preventing discouragement. Buddhi-dhrita (firmly grasped intelligence) guiding process-patient intelligent progression. Uparamet (cessation of material engagement) happens progressively not instantly. Therefore accept gradual development-measure progress over months/years not days/weeks, maintaining patient consistent practice without frustration from immediate-result expectations, trusting process over time."
}

print("=== Chapter 6 Enhancement ===")
q6 = enhance_chapter(6, ch6_enhancements)

# === CHAPTER 7 ENHANCEMENTS === (Refining ~6 questions to push from 76% to 90%+)
# Will target questions currently lacking both trap and false path
ch7_enhancements = {
    "bg7-q1": "Asaktena (without attachment), mat-parah (devoted to Me)-practicing yoga hearing about Me-will know entirely. The trap: knowledge accumulation without devotional context. Why this matters: The false path is academic Krishna-study-learning philosophy/theology without mat-parah (devotional orientation), producing theoretical knowledge not transformative realization. Real understanding: Complete knowledge (asamshayam samagram) requires asaktena (detached from material) plus mat-parah (devoted to Krishna)-devotional relationship providing framework for genuine understanding. Hearing about Krishna (mayi shrinvat) in devotional consciousness enables complete realization. Therefore approach Krishna-knowledge devotionally-not as subject for study but as Person for relationship, transforming information-gathering into devotional realization.",

    "bg7-q5": "Beyond apara (lower material) prakrti is para (higher spiritual) prakrti-jiva-bhutah (living entities) sustaining jagat (world). The trap: monistic oneness. Why this matters: The false path is undifferentiated Brahman-declaring living entities identical with Supreme, missing para-prakrti (superior nature) distinction from apara-prakrti (inferior nature). Real understanding: Living entities constitute para-prakrti (superior spiritual nature) distinct from apara-prakrti (eight material elements)-higher than matter but subordinate to Supreme. Neither material (apara) nor Supreme but intermediate category-simultaneously one and different. Therefore understand acintya-bhedabheda-living entities ontologically distinct from both matter and Supreme, occupying intermediate position as Supreme's eternal marginal energy.",

    "bg7-q12": "Sattva/rajas/tamas bhavas (states)-all from Me eva (alone), but not I in them, they in Me. The trap: pantheistic immanence without transcendence. Why this matters: The false path is limiting Krishna to material manifestations-'God is in everything' without recognizing He transcends everything, reducing Supreme to material categories. Real understanding: Modes originate mattah (from Me) but na aham teshu (not I in them)-Krishna source of gunas but transcends them. Asymmetrical relationship-modes depend on Krishna, Krishna independent of modes. This preserves both immanence (modes from Krishna) and transcendence (Krishna beyond modes). Therefore recognize Krishna's simultaneous immanence-transcendence-present in creation as source yet untouched by creation's limitations, neither pantheistic reduction nor deistic distance.",

    "bg7-q15": "Na mam dushkritinah (evildoers not to Me) prapadyante (surrender)-four types: mudha (foolish), naradhama (lowest), mayayapahrita-jnanah (knowledge stolen by maya), asuram (demonic). The trap: universal divine acceptance regardless of character. Why this matters: The false path is sentimental universalism-'everyone worships same God'-missing that character-defects prevent Krishna-surrender. Real understanding: Four obstacles-mudhah (foolish materialists), naradhama (degraded misusing human life), mayayapahrta-jnanah (pseudo-intellectual with distorted knowledge), asuricam bhavam ashritah (those accepting demoniac nature)-all avoid surrendering to Krishna. Character matters-certain corruptions prevent spiritual receptivity. Therefore cultivate receptive character-overcoming foolishness/degradation/distorted-knowledge/demoniac-mentality enabling Krishna-surrender, recognizing spiritual path requires character-development not just intellectual assent.",

    "bg7-q18": "All four devotee-types (arta/artharthi/jijnasu/jnani) are udara (noble), but jnani is atmaiva (My very self)-most dear. The trap: equal-value relativism among devotees. Why this matters: The false path is treating all devotional motivations equally-missing progressive hierarchy from material distress-relief through enlightenment-seeking to pure love. Real understanding: All four types noble-distressed, materially desirous, curious, wise-but jnani in pure love is atmaiva Me iti (My very self). Qualitative progression-begin with material motives, gradually purify to unmotivated devotion. Jnani prioritized not from favoritism but from love-quality. Therefore aim for jnana-bhakti-appreciate all devotional beginning-points while aspiring toward unmotivated pure love, recognizing spiritual path's developmental nature from mixed to pure motivation.",

    "bg7-q19": "After bahuni janmani (many births), jnani (wise one) knowing vasudevah sarvam (Vasudeva is all) surrenders-such mahatma su-durlabhah (very rare). The trap: instant enlightenment or common attainment. Why this matters: The false path is either expecting immediate realization or assuming many achieve it-missing that genuine Krishna-surrender after complete understanding is su-durlabhah (extremely rare). Real understanding: Bahuni janmani (many births) required for full realization-not quick achievement but gradual development over multiple lifetimes. Vasudevah sarvam iti (Vasudeva is everything)-complete understanding enabling total surrender. Such mahatma very rare-acknowledges path's difficulty preventing false claims or discouragement. Therefore maintain realistic expectations-genuine realization rare and gradual, inspiring sustained effort without illusions of easy achievement or false success-declarations."
}

print("\n=== Chapter 7 Refinement ===")
q7 = enhance_chapter(7, ch7_enhancements)

# === CHAPTER 8 ENHANCEMENTS === (Refining ~5 questions to push from 80% to 90%+)
ch8_enhancements = {
    "bg8-q2": "Adhiyajna (Lord of sacrifice) here in deha (body)-identified as Krishna-known by yukta-cetasah (disciplined consciousness) at anta-kale (time of death). The trap: disembodied spirituality. Why this matters: The false path is abstract theology divorced from embodied practice-thinking sacrifice-philosophy sufficient without recognizing Krishna's personal presence in heart, missing practical devotional relationship. Real understanding: Adhiyajna (Lord of sacrifice) is aham eva (I alone, Krishna) atra (here) in deha (this body)-personal presence not abstract principle. Yukta-cetasah (those with disciplined consciousness) know this anta-kale (at death's time)-preparedness through relationship. Therefore cultivate present awareness of Krishna in heart-not future knowledge but current relationship enabling death-time remembrance, embodied practice grounding abstract philosophy.",

    "bg8-q5": "Anta-kale (end time) remembering Me alone leaving deha (body)-attains mad-bhava (My nature), no sanshaya (doubt) in this. The trap: lifetime behavior irrelevant if death-remembrance correct. Why this matters: The false path is deathbed conversion theory-living materially then trying Krishna-remembrance at death, missing that anta-kale memory depends on lifetime cultivation. Real understanding: Yam yam vapi smaran bhavam (whatever state remembering) tyajati ante kalebaram (leaves body at end)-determines destination. But death-remembrance isn't isolated event-reflects lifetime consciousness-cultivation. Therefore practice continuous remembrance-death-time consciousness reflects lifetime practice, cultivate now what you want to remember then, recognizing final moment as harvest of lifetime's cultivation not independent wild-card.",

    "bg8-q7": "Therefore sarveshu kaleshu (at all times) remember Me, fight with mad-arpita-mano-buddhih (mind-intelligence offered to Me)-mam eva eshyasi (certainly will come to Me). The trap: either-or thinking: devotion OR duty. Why this matters: The false path is abandoning duties for remembrance-thinking Krishna-consciousness requires activity-cessation, missing integrated approach. Real understanding: Sarveshu kaleshu (all times) mam anusmara (remember Me) yudhya ca (and fight also)-simultaneous remembrance and duty-performance. Mad-arpita-mano-buddhih (mind-intelligence offered to Me)-transforms fighting into devotional service. Therefore practice integrated spirituality-don't abandon duties for devotion but perform duties with devotion, sanctifying action through Krishna-consciousness maintaining activities while transforming consciousness.",

    "bg8-q14": "Ananya-cetah (without other thoughts) satatam (constantly) remembering-easy to reach for nitya-yuktasya (constantly engaged) yogin. The trap: part-time devotion suffices. Why this matters: The false path is occasional Krishna-consciousness-thinking sporadic remembrance adequate while primarily materially absorbed, missing continuous practice requirement. Real understanding: Ananya-cetah (undivided consciousness) satatam (constantly) remembering produces su-labhah (easy attainment)-continuous not occasional. Nitya-yukta (constantly engaged) yogin-uninterrupted practice over time. Constant engagement makes difficult easy. Therefore cultivate continuous practice-not just formal sessions but persistent background Krishna-awareness throughout all activities, measuring advancement by baseline consciousness-level not peak devotional experiences.",

    "bg8-q16": "A-brahma-bhuvanat lokah (worlds up to Brahmaloka) punar-avrttayah (subject to rebirth)-reaching Me na punar janma (no rebirth) Arjuna. The trap: heavenly-worlds as ultimate goal. Why this matters: The false path is celestial-destination fixation-seeking Brahmaloka/Svarga as final achievement, missing they remain within material rebirth-cycle. Real understanding: Even a-brahma-bhuvanat (up to Brahmaloka) all lokah (worlds) punar-avrittayah (subject to return)-impermanent. Only mam upetya (reaching Me) na punar janma (no rebirth)-Krishna's abode alone permanent. This exposes heavenly-goal inadequacy. Therefore transcend celestial ambitions-don't aim for temporary elevated positions but permanent liberation through Krishna-attainment, recognizing even highest material destination eventually leads back to birth-death cycle.",

    "bg8-q28": "Knowing this tattvatah (in truth) yogi overcomes punyam-phalam (results of piety) from Vedas/yajnas/tapas/dana-returning to sanatana parama-pada (eternal supreme abode). The trap: piety-accumulation path. Why this matters: The false path is karma-kanda gradualism-slowly accumulating punya (merit) over many births hoping eventual elevation, missing transcendental knowledge enables immediate transcendence. Real understanding: Understanding this tattva (truth) yogi atyeti (transcends) all punyam-phalam (pious results)-doesn't gradually accumulate but directly transcends material platform. Sanatana paramam sthanam (eternal supreme abode) reached through knowledge not through piety-accumulation. Therefore seek knowledge-based liberation-transcend pious-work platform through tattva-jnana enabling direct access to spiritual realm, not gradual material elevation through merit-accumulation requiring countless births."
}

print("\n=== Chapter 8 Refinement ===")
q8 = enhance_chapter(8, ch8_enhancements)

print(f"\n✅ CHAPTERS 6-7-8 COMPLETE")
print(f"Ch6 quality={q6:.0f}% (49%→{q6:.0f}%)")
print(f"Ch7 quality={q7:.0f}% (76%→{q7:.0f}%)")
print(f"Ch8 quality={q8:.0f}% (80%→{q8:.0f}%)")
print("\n🎉 ALL 8 CHAPTERS enhanced with expert critique patterns!")
print("Trap → False path → Real understanding applied throughout")
