"""
Enhance BG Ch4-5-6 feedback to expert critique level
Ch4: 8% -> 90%+ (parampara, avatara, yajna, jnana-karma synthesis)
Ch5: 15% -> 90%+ (sannyasa vs karma-yoga, brahma-bhuta, sama-darshana)
Ch6: 49% -> 90%+ (dhyana-yoga, mind control, unsuccessful yogi)
"""
import json

def enhance_chapter(ch_num, enhancements):
    fname = f'data/quizzes/bg/{ch_num}-adult.json'
    with open(fname) as f:
        data = json.load(f)
    
    for q in data['questions']:
        qid = q['id']
        if qid in enhancements:
            q['feedback'] = enhancements[qid]
    
    with open(fname, 'w') as f:
        json.dump(data, f, indent=2)
    
    # Validate quality
    trap = sum(1 for q in data['questions'] if 'trap' in q.get('feedback','').lower())
    fp = sum(1 for q in data['questions'] if 'false path' in q.get('feedback','').lower())
    total = len(data['questions'])
    quality = ((trap + fp + total) / (total * 3)) * 100
    
    print(f"✅ Ch{ch_num} enhanced: trap={trap}/{total}, fp={fp}/{total}, quality={quality:.0f}%")
    return quality

# === CHAPTER 4 ENHANCEMENTS ===
ch4_enhancements = {
    "bg4-q1": "Krishna declares imaम् vivasvate yogam proktavan (I spoke this yoga to Vivasvan)-establishes ancient parampara. The trap: novelty-seeking modernity bias. Why this matters: The false path is assuming newer is truer-treating ancient teachings as primitive, requiring 'modern' revision for relevance. Real understanding: Timeless truth transmitted through disciplic succession (parampara) from Krishna -> Vivasvan -> Manu -> Ikshvaku demonstrates knowledge's eternal nature and authentic transmission-method. Not human speculation evolving over time but divine revelation maintained through authorized lineage. This validates Vedic epistemology-knowledge descends from perfect source (Krishna) through transparent media (realized gurus), not ascending from imperfect speculation. Therefore approach transcendental knowledge through parampara not independent research-truth isn't discovered but received from knowers.",
    
    "bg4-q2": "Parampara (disciplic succession) maintains knowledge evam paramparaya (thus in succession)-prevents deviation. The trap: autonomous interpretation. Why this matters: The false path is treating scripture as open text for individual interpretation-assuming sincere reading suffices without lineage-authorization, producing fragmentation and distortion. Real understanding: Realization requires guru-parampara transmission-not just reading words but receiving understanding from those who received from their gurus back to original speaker. Prevents distortion through unauthorized interpretation-like telephone-game, message corrupts without authorized relay. Sa kaleneha yogo nashtah (with time this yoga was lost) shows deviation's inevitability without living tradition. Therefore receive knowledge through bona-fide parampara not independent study-lineage ensures fidelity to original meaning against time's corrupting influence.",
    
    "bg4-q3": "Krishna declares Arjuna as bhaktosi (My devotee) and sakha (friend)-qualifications for receiving confidential knowledge. The trap: qualification-irrelevance assumption. Why this matters: The false path is democratizing transcendental knowledge-assuming any sincere seeker regardless of consciousness qualifies for highest teachings, missing preparedness requirement. Real understanding: Guhyam (confidential) knowledge requires appropriate receiver-not elitist restriction but practical necessity. Bhakti (devotion) and friendship with Krishna create receptivity theoretical knowledge cannot-relationship precedes realization. Impersonalists studying same words miss meaning because lacking devotional platform. Therefore cultivate devotional relationship before expecting full realization-qualification matters not from pride but from epistemic necessity that consciousness-level determines comprehension-depth.",
    
    "bg4-q4": "Arjuna's chronological objection-how could You instruct Vivasvan when he lived previously? The trap: historical-critical reductionism. Why this matters: The false path is applying material time-constraints to spiritual beings-assuming Krishna subject to linear chronology like conditioned souls, reducing Him to historical figure. Real understanding: Krishna is nitya (eternal) and ajam (unborn)-exists beyond time as its source. Appeared in past kalpas (time-cycles) performing identical lilas (pastimes) including instructing Vivasvan. Material chronology doesn't constrain Him-can appear/disappear at will throughout time. This demonstrates avyayam (inexhaustible) nature-not depleted or changed by manifestation. Therefore transcend chronological provincialism-Krishna isn't historical personage but eternal person occasionally visible in history, existing equally in all time-periods simultaneously.",
    
    "bg4-q5": "Verse distinguishes Krishna (veda-aham-I know) from Arjuna (na vettha-you don't know) regarding past births-qualitative difference. The trap: egalitarian relativism. Why this matters: The false path is assuming Krishna-Arjuna differ only quantitatively (realized vs unrealized) not qualitatively-missing that Krishna is Supreme (never conditioned) while Arjuna is jiva (conditioned but recoverable). Real understanding: Krishna possesses complete memory of infinite births because never covered by maya; Arjuna forgets due to material conditioning. Not developmental difference (both advancing at different rates) but constitutional difference (ever-free vs conditionally-bound). This establishes Krishna's supreme position-not another seeker but eternal Teacher possessing perfect omniscience. Therefore accept Krishna as Supreme Authority not fellow-traveler-relationship requires acknowledging ontological distinction enabling instruction-reception.",
    
    "bg4-q6": "Krishna as ajo'vyayatma (unborn, inexhaustible soul) and bhutanam ishvara (Lord of beings) appears through yoga-maya. The trap: ordinary birth comparison. Why this matters: The false path is treating Krishna's appearance as material birth-soul entering womb, undergoing gestation, subject to karma-missing transcendental nature of avatar. Real understanding: Krishna doesn't take birth (ordinary jiva) but appears (descends)-atma-maya (internal potency) manifests His eternal form without material contamination. Ishvara (controller) not controlled-chooses when/where to appear unlike conditioned souls forced by karma. This preserves divinity-if Krishna born materially, He'd be conditioned entity not Supreme Lord. Therefore Krishna's appearance is lila (transcendental pastime) not karma (material consequence)-descends voluntarily to re-establish dharma, not forced by previous actions.",
    
    "bg4-q7": "Krishna appears yada yada hi dharmasya glanir bhavati (whenever decline of dharma)-principle of periodic descent. The trap: dispensability thesis. Why this matters: The false path is assuming Krishna's appearance historically contingent not necessary-maybe happened, maybe not-reducing avatara to optional myth. Real understanding: Regular incarnation (avatara) constitutes cosmic maintenance-system-Krishna descends precisely when dharma declines, establishing rhythm of revelation-decline-restoration. Not random but systematic-like seasonal rains occurring when needed. This demonstrates Krishna's ongoing involvement-not deist God creating then abandoning but active maintainer periodically intervening. Therefore avatara-principle shows divine care-system-Krishna doesn't leave creation to independent evolution but actively guides through periodic incarnations maintaining dharmic order.",
    
    "bg4-q8": "Krishna's dual purpose-paritranaya sadhunam (protect devotees) and vinashaya dushkritam (destroy miscreants). The trap: sentimentalized unilateral mercy. Why this matters: The false path is projecting only loving acceptance-assuming Krishna tolerates all behaviors equally, missing justice dimension. Real understanding: Krishna simultaneously merciful (protecting sadhus) and just (destroying dushkritam)-not contradiction but completeness. Evil requires active opposition not passive acceptance-neglecting this enables adharma's spread. Devotees need protection from oppression; miscreants need destruction for collective welfare. Therefore Krishna's mercy includes justice-protecting good requires removing evil, authentic compassion sometimes manifests as apparent severity preventing harm to innocent and correcting wrongdoers.",
    
    "bg4-q9": "Knowing Krishna's transcendental birth (divyam) and activities (karma) liberates-tyaktva deham punar janma naiti (leaving body, doesn't take birth again). The trap: biographical knowledge sufficiency. Why this matters: The false path is treating Krishna-lila as mere history-studying facts without devotional understanding, producing academic knowledge not liberating realization. Real understanding: Divyam means transcendental-Krishna's activities aren't mundane events but spiritual substance. Knowing them tattvatah (in truth) requires devotional consciousness not just intellectual comprehension. This knowledge alone liberates-such power indicates content's transcendental nature, not ordinary information. Mam eti (comes to Me)-liberation means personal relationship not impersonal absorption. Therefore approach Krishna's pastimes devotionally-hearing/chanting with bhakti enables transcendental realization transforming knowledge into liberation.",
    
    "bg4-q10": "Vita-raga-bhaya-krodha (free from attachment-fear-anger), mam-mayah (absorbed in Me)-purification through bhakti. The trap: negative-definition spirituality. Why this matters: The false path is cessation-focused practice-trying to eliminate negatives (raga/bhaya/krodha) without cultivating positive (Krishna-absorption), producing emptiness not fulfillment. Real understanding: Purification isn't mere subtraction (removing bad qualities) but substitution (replacing material absorption with Krishna-absorption). Mam-mayah indicates positive cultivation-consciousness filled with Krishna leaving no space for material contaminations. Tapasa (austerity) works when directed toward Krishna not merely away from material. Therefore positive bhakti naturally eliminates negatives-occupied consciousness in Krishna automatically becomes unoccupied in material, achieving purification through engagement not renunciation.",
    
    "bg4-q11": "Ye yatha mam prapadyante (as they surrender to Me), tams tathaiva bhajami (I reward proportionally)-reciprocation principle. The trap: unilateral divine action. Why this matters: The false path is either demanding Krishna act irrespective of one's surrender, or fearing Krishna won't respond to sincere approach-both missing reciprocal relationship structure. Real understanding: Krishna reciprocates according to surrender-degree-intense devotee receives intense reciprocation, casual seeker receives casual response. Not capricious but lawful-like mirror reflecting viewer precisely. This validates effort-Krishna responds to whatever approach offered. Mama vartma (My path)-various paths ultimately reach Him because He accepts sincere seekers through any authorized process. Therefore Krishna's reciprocation guarantees result proportional to input-removes doubt about practice's effectiveness while establishing responsibility for intensity.",
    
    "bg4-q12": "Those desiring fruitive results (kankshantah karmanam siddhim) worship devas-material orientation. The trap: material spirituality. Why this matters: The false path is using spiritual practices for material goals-treating devas as means to wealth/power/pleasure, remaining on material platform while appearing religious. Real understanding: Demigod-worship for fruitive results (kamya-karma) keeps consciousness material-goal determines path's nature, not ritual's sophistication. Quick results in human society (ksipram) indicate material not spiritual success-transcendental realization develops gradually through purification. This exposes motivation-test-are religious activities pursued for material benefits or spiritual transformation? Therefore examine worship's purpose-if seeking material results, remains material consciousness; only Krishna-prema as goal produces transcendental consciousness-shift.",
    
    "bg4-q13": "Catur-varnyam (four orders) created maya (by Me) according to guna-karma (quality-work)-divine social organization. The trap: biological determinism or arbitrary social construction. Why this matters: The false path is either birth-based rigidity (varna by genetics alone) or radical constructivism (varna as oppressive fiction)-missing divinely ordained yet quality-based system. Real understanding: Varnashrama created by Krishna according to guna (quality) and karma (activity)-not birth nor arbitrary social agreement but divinely designed social order reflecting individual's psychophysical nature. Brahmana/kshatriya/vaishya/shudra determined by qualities demonstrated and work performed-validates natural diversity while preventing exploitation. Akarataram api mam viddhi akartaram avyayam (though creator, know Me as non-doer and eternal)-Krishna establishes system then allows it to function through nature. Therefore follow varnashrama-dharma according to actual qualities-divinely designed social order facilitating both material stability and spiritual advancement when properly understood.",
    
    "bg4-q14": "Na mam karmani limpanti (actions don't bind Me), na me karma-phale spriha (I have no desire for action-fruits)-Krishna's transcendence. The trap: analogizing Krishna's action to jiva's. Why this matters: The false path is treating Krishna's activities as analogous to conditioned souls'-assuming He acts from desire/necessity like us, reducing Him to superhuman not Supreme. Real understanding: Krishna acts without binding karmic reactions because no selfish motivation-na spriha (desireless). Actions without desire for results don't produce bondage-principle applicable both to Krishna (eternally) and jiva (through cultivation). Ittham yah mam vetti na sa karmabhir badhyate (one who knows thus isn't bound by activities)-understanding Krishna's transcendence enables one's own transcendence through imitation. Therefore emulate Krishna's desirelessness-acting without result-attachment, transforming actions from binding to liberating through consciousness-purification.",
    
    "bg4-q15": "Ancient siddhas (perfected beings) performed action knowing this tattva (truth)-precedent for karma-yoga. The trap: unprecedented individual path. Why this matters: The false path is assuming successful spirituality requires inventing personal method-missing that authorized path already tested by countless predecessors. Real understanding: Evam (thus) purva (ancient) siddhas (perfected) practiced karma-yoga achieving liberation-validates method through results. Not blind traditionalism but evidence-based confidence-proven process repeatedly producing desired outcome. Kuru karma (perform action) tasmad tvam (therefore you) purvaih purvataram (as ancients did earlier)-follow established effective procedure rather than experimental novelty. Therefore trust proven path-ancient siddhas' success demonstrates karma-yoga's effectiveness, providing confidence for current practice against novel untested alternatives.",
    
    "bg4-q16": "Kim karma kim akarmeti (what is action, what is inaction)-wise are bewildered about action's nature. The trap: superficial behavioral ethics. Why this matters: The false path is action-inaction based solely on external behavior-treating physical movement as action, physical stillness as inaction-missing consciousness determines action's actual nature. Real understanding: Complexity requires guru-guidance-apparently doing nothing while consciousness absorbed in material is action (binding); apparently doing everything while consciousness absorbed in Krishna is inaction (non-binding). Karmano gahana (action's nature is profound) indicates philosophical sophistication required. Dhira (wise) can be mohita (bewildered) showing this isn't obvious. Therefore seek expert guidance discerning karma (binding action) from akarma (liberating non-action)-external appearance doesn't reveal consciousness-quality determining spiritual effect.",
    
    "bg4-q17": "Must understand karma (action), vikarma (forbidden action), and akarma (inaction)-threefold discrimination. The trap: binary thinking about action. Why this matters: The false path is simple action/inaction dichotomy-missing nuanced classification where forbidden action (vikarma) differs from prescribed action (karma), and transcendental action appears as non-action (akarma). Real understanding: Three categories-karma (prescribed duties binding if performed selfishly), vikarma (prohibited acts always binding), akarma (devotional service appearing as action but non-binding). Gahana karmano gatih (profound is the way of action)-requires subtle discrimination beyond gross behavior-observation. Therefore develop discriminative intelligence through guru-shastra-sadhu-distinguishing actions' spiritual quality not just their external form, enabling navigation of complex ethical landscape.",
    
    "bg4-q18": "Seeing action in inaction and inaction in action-paradoxical transcendental vision. The trap: conventional perception. Why this matters: The false path is surface-level observation-assuming external activity indicates binding action, external stillness indicates liberation-missing consciousness determines action's actual effect. Real understanding: Transcendentally situated person sees akarma (non-action) in karma (action)-engaged physically but uninvolved emotionally/volitionally, no binding result. Simultaneously sees karma in akarma-apparently doing nothing while consciousness full of material thoughts accumulates karma. This inverted vision reveals consciousness supremacy over behavior-what you think while acting determines result more than what you do. Buddhiman (intelligent) manushyeshu (among humans) yuktah (engaged) krisnakrit (all-work-doer)-actively engaged yet transcendental. Therefore cultivate conscious Krishna-connection during all activities-transforms binding actions into non-binding service through consciousness-quality regardless of external behavior.",
    
    "bg4-q19": "Sarvarambha (all undertakings) without kama-sankalpa (desire-conception)-actionin desireless consciousness. The trap: inactive cessationism. Why this matters: The false path is thinking desireless means doing nothing-confusing desirelessness with inactivity, producing artificial withdrawal. Real understanding: Sarvarambha means all undertakings-not no undertakings-but performed without kama (selfish desire) and sankalpa (mental motivation for results). Full external engagement with internal transcendence-working without working. Panditah (wise) call such person-not because avoiding action but because performing action transcendentally. Therefore maintain full activity spectrum while eliminating selfish motivation-doesn't require behavior-reduction but consciousness-transformation, performing all duties without material attachment.",
    
    "bg4-q20": "Tyaktva karma-phalasangam (abandoning results-attachment), nitya-tripto (always satisfied), nirashraya (without shelter)-appears actionless while fully engaged. The trap: external renunciation. Why this matters: The false path is interpreting renunciation as activity-cessation-missing that internal detachment not external withdrawal defines real tyaga. Real understanding: Abandons phalasanga (result-attachment) not karma (action itself)-performs duties without expecting personal benefit. Nitya-tripto internally satisfied-doesn't need action-results for happiness. Nirashraya without material shelter-doesn't depend on outcomes for security. Karmani abhipravrittah api (engaged in activities nevertheless) naiva kinchit karoti (does nothing at all)-paradox resolved through consciousness-quality. Therefore renounce attachment not action-inner freedom maintaining outer engagement, transforming karma from bondage into non-bondage through desireless performance.",
    
    "bg4-q21": "Nirasir (without expectation), yatcitta (controlled mind), tyakta-sarva-parigraha (abandoned possessiveness)-performs only bodily action without karmic consequence. The trap: external action inevitably produces karma. Why this matters: The false path is assuming any physical activity generates binding karma-missing that consciousness determines binding-power not behavior. Real understanding: Controlled mind without expectation/possessiveness performs shariram kevalam (body alone) action-physical movements without volitional investment, preventing karmic reaction. Papam (sin) doesn't touch such person because sin requires willful violation-mechanical action without desire/attachment carries no moral weight. This liberates from paralytic fear of action-can engage fully without karmic anxiety when consciousness properly situated. Therefore perform duties with controlled consciousness-not action itself but consciousness during action determines karma, enabling fearless engagement in prescribed duties.",
    
    "bg4-q22": "Content with spontaneous gain (yadriccha-labha), beyond dualities (dvandva-atita), equipoised (sama), non-envious (na matsari)-liberated though acting. The trap: achievement-orientation pervades spiritual life. Why this matters: The false path is bringing material success-mentality into spiritual practice-planning/strategizing for specific outcomes, remaining result-focused though religiously. Real understanding: Yadriccha-labha santushta (content with spontaneous gain)-accepts whatever comes without scheming for more. Beyond dvandva (dualities like gain/loss, success/failure)-equal-minded in all circumstances. This contentment-freedom produces mukta (liberation) even while performing karma-not waiting for future liberation but liberated now through present contentment. Therefore cultivate satisfaction with present arrangements-cease material planning-mentality even in spiritual activities, accepting Krishna's arrangement as perfect for spiritual advancement regardless of appearance.",
    
    "bg4-q23": "Gatasangasya muktasya (freed from attachment, liberated) whose mind established in jnana-work dissolves in yajna. The trap: accumulated karma-debt requires payment. Why this matters: The false path is fearing past karma's inevitable consequences-assuming accumulated reactions must be suffered, producing anxiety despite present spiritual practice. Real understanding: For liberated person (mukta) whose consciousness anchored in transcendental knowledge, all work dissolves into sacrifice (akhilam karma akhilam samapyate)-past reactions neutralized through present transcendental consciousness. Not gradual payment through suffering but complete dissolution through knowledge. This removes retroactive karma-fear-present realization neutralizes past reactions, enabling anxiety-free practice. Therefore don't fear past karma-genuine transcendental consciousness dissolves previous entanglements, focusing energy on present purification not past consequences.",
    
    "bg4-q24": "Brahmarpanam (Brahman is the offering), brahma-havi (Brahman is the oblation), brahmagnau (in fire of Brahman), brahmana (by Brahman), hutam (offered)-all is Brahman in transcendental vision. The trap: pantheistic monism. Why this matters: The false path is undifferentiated oneness-declaring 'all is Brahman' in impersonal sense, eliminating distinctions necessary for relational worship. Real understanding: Person in Brahman-consciousness sees everything in relation to absolute-offering/oblation/fire/offerer all understood as Brahman's energy engaged in Brahman's service. Not that distinctions disappear but that all distinctions relate to single source. Brahmaiva tena gantavya (Brahman alone is reached) by such consciousness-seeing unity-in-diversity. Therefore develop Brahman-vision-seeing all as Krishna's energy engaged in His service, not eliminating variety but understanding variety's source and purpose.",
    
    "bg4-q25": "Various yajnas-daivam (demigod-worship), brahma (Brahman offerings)-show diverse valid spiritual approaches. The trap: my-way-only sectarianism. Why this matters: The false path is exclusivist rigidity-declaring only one valid spiritual process, dismissing all others as useless-producing religious conflict and limiting accessibility. Real understanding: Krishna acknowledges multiple valid paths-daiva-yajna (demigod worship), brahma-yajna (offering to Brahman), samyama-yajna (sense-control), and others-all have value at appropriate levels. Unity in diversity-various practices suit various temperaments/stages while ultimately reaching same goal. This doesn't mean all paths equal but that various authorized paths exist. Therefore respect diverse approaches while following one's own-avoid sectarian rejection of alternative authorized processes, recognizing that what works for one may not work for another, yet all can be valid."
}

print("=== Chapter 4 Enhancement ===")
q4 = enhance_chapter(4, ch4_enhancements)

# === CHAPTER 5 ENHANCEMENTS ===
ch5_enhancements = {
    "bg5-q1": "Arjuna asks tray shreyah (which is better)-sannyasa (renunciation) or karma-yoga (engaged work). The trap: either/or dichotomy forcing exclusive choice. Why this matters: The false path is treating spiritual paths as competing alternatives requiring rejection of one for the other-missing that for most practitioners karma-yoga provides practical approach while sannyasa requires advanced qualification. Real understanding: Question reveals lingering confusion despite Ch3-4 teaching-still seeing paths as contradictory not complementary. Krishna will clarify both lead to same goal but karma-yoga more accessible for most-not absolute superiority but practical superiority given human conditioning. Therefore don't force premature either/or spiritual decisions-understand various paths' relative applicability to current situation rather than seeking single universal answer.",
    
    "bg5-q2": "Krishna declares both sannyasa and karma-yoga reach same goal but karma-yoga is durakaram (difficult to achieve) without work. The trap: inaction-path superiority assumption. Why this matters: The false path is romant romanticizing renunciation-thinking cessation automatically produces transcendence, missing that inactive renunciation without purification produces only frustration. Real understanding: Sannyasa without purified consciousness is durakaram (difficult/painful)-restless mind creates mental suffering. Karma-yoga purifies naturally through engaged service, making subsequent renunciation authentic rather than forced. Not opposing paths but sequential-karma-yoga prepares consciousness for genuine sannyasa. Therefore don't artificially attempt renunciation before internal preparation-engage in karma-yoga purifying consciousness, enabling natural renunciation when ready rather than forced premature withdrawal.",
    
    "bg5-q3": "Karma-yogi neither hates (na dveshti) nor desires (na kankshati)-transcends dvandva (dualities) easily. The trap: emotional suppression equals transcendence. Why this matters: The false path is forced emotional neutrality-artificially suppressing like/dislike through willpower, producing brittle detachment requiring constant maintenance. Real understanding: Natural transcendence from karma-yoga engagement-consciousness absorbed in service naturally becomes disinterested in dualities' pull. Not fighting reactions but transcending through higher taste-Krishna connection provides satisfaction making dvandva-push-pull irrelevant. Sukham bandhad pramuchyate (easily freed from bondage)-ease indicates natural process not forced discipline. Therefore cultivate Krishna-centered activity generating natural dvandva-transcendence-engagement in service automatically reduces material reaction, achieving equanimity through occupations not suppression.",
    
    "bg5-q4": "Children distinguish (prithag vadanti) sankhya from yoga; wise see both reach same destination. The trap: sectarian path-superiority claims. Why this matters: The false path is treating different paths as inherently superior/inferior-producing sectarian conflict and discouraging practitioners on valid alternative paths. Real understanding: Panditas (wise) see ekam (oneness)-various paths reach identical goal when practiced properly. Distinction is implementation not destination-some prefer contemplative sankhya, others active karma-yoga, both valid. Balavah na panditah (children not wise)-immature create false conflicts where wise see unity. Therefore transcend immature sectarianism-recognize multiple valid paths while following one's own, avoiding superiority claims producing division among sincere spiritual practitioners pursuing same ultimate goal through different means.",
    
    "bg5-q5": "Sannyasinas (renunciant's) position reached by karma-yogins (engaged workers)-same goal different routes. The trap: result-determinism from method. Why this matters: The false path is thinking method determines result absolutely-assuming only renunciants reach liberation, workers remain bound-missing consciousness-quality trumps external lifestyle. Real understanding: Yat (what) sannyasaih (by renunciates) prapyate (is reached), tat (that) yogaih (by workers) prapyate (is reached)-identical destination. One transcends through withdrawal, other through engaged service-both valid when consciousness properly oriented to Krishna. Method matters less than motivation-detached work equals attached renunciation in spiritual ineffectiveness, attached work equals detached renunciation in binding power. Therefore focus on consciousness-quality during practice not external form-properly motivated work equals properly motivated renunciation in liberating power.",
    
    "bg5-q6": "Sannyasa without yoga (devotional action) is duhkham (miserable)-negative renunciation doesn't satisfy. The trap: negation suffices for spirituality. Why this matters: The false path is cessation-focused practice-renouncing material without cultivating spiritual, producing vacuum not fulfillment. Real understanding: Mere renunciation (sannyasa without yoga) creates duhkham (suffering)-empty consciousness abhors vacuum, pulls back toward material. Yoga-yukta munir (sage engaged in devotional service) reaches Brahman quickly-positive cultivation prevents backslide. This demonstrates positive-negative balance necessity-can't sustain long-term purely negative practice. Therefore pair renunciation with cultivation-reduce material engagement while increasing spiritual engagement, preventing suffering-vacuum that defeats renunciation by pulling consciousness back to material for occupational relief.",
    
    "bg5-q7": "Yoga-yukta (engaged in devotional service), vishuddhatma (purified self), vijitatma (controlled self), sarva-bhuta-atma-bhuta (realizing all beings as self)-untainted though acting. The trap: action inevitably contaminates. Why this matters: The false path is assuming activity necessarily produces material attachment-requiring withdrawal for purity, missing that consciousness-quality determines contamination not behavior. Real understanding: Properly oriented person (yoga-yukta, purified consciousness, controlled senses) performs work without taint-karma doesn't bind one seeing all beings' self-nature. Not action but attached action contaminates-detached action purifies. This liberates from action-paralysis fear-can engage fully without anxiety when consciousness properly situated. Therefore purify consciousness through devotional engagement-enables fearless action knowing that right consciousness prevents karmic entanglement regardless of activity-intensity.",
    
    "bg5-q8": "Transcendentally situated (tattva-vit) thinks 'na eva kinchit karomi' (I do nothing at all) even while actively seeing/hearing/walking/sleeping. The trap: delusion of inactivity. Why this matters: The false path is either literal interpretation (actually doing nothing) or false-ego claim (doing everything but declaring non-doership)-missing transcendental non-agency realization. Real understanding: Tattva-vit (knower of truth) understands indriyani (senses) indriyartheshu (among sense objects) vartante iti (thus move)-material nature through sense-instruments performs actions, self as witness not agent. Not false humility ('I did nothing' while claiming credit internally) but ontological accuracy-recognizing prakrti performs while purusha observes. Therefore realize constitutional position-neither false agent claiming doership nor false actor pretending non-agency, but authentic witness recognizing material nature executes actions under Supreme direction while self observes transcendentally.",
    
    "bg5-q9": "Brahmani adhaya (fixing in Brahman) karmani (actions), sangam (attachment) tyaktva (abandoning)-lotus leaf not water-touched. The trap: world-avoidance spirituality. Why this matters: The false path is physical withdrawal assuming contact produces contamination-requiring isolation for purity, missing consciousness determines taint not proximity. Real understanding: Padma-patram iva ambhasa (like lotus leaf on water)-remain in material world without material contamination through Brahman-consciousness. Not rejecting world but engaging detachedly-lotus grows in water, used by water for support, yet water doesn't stick. Similarly engage in material duties without material attachment. This enables householder-spirituality-needn't abandon responsibilities for liberation when consciousness properly situated. Therefore cultivate Brahman-consciousness amid worldly engagement-transforms duty-performance from binding to non-binding through consciousness-shift maintaining external involvement.",
    
    "bg5-q10": "Performs duty as offering to Brahman, abandoning attachment-na lipyate (unattached) like lotus. The trap: contamination-inevitability from contact. Why this matters: The false path is contagion-model of material association-assuming any worldly contact produces taint requiring physical separation, missing consciousness creates separation more effectively than distance. Real understanding: Repeats lotus metaphor emphasizing Brahman-offering transforms ordinary activity-performing duty brahmani adhaya (fixing in Brahman), sangam tyaktva (abandoning attachment) prevents papena (by sin) contamination. Not activity but attached activity contaminates-detached engagement remains pure. Therefore sanctify duties through Brahman-consciousness-offering to Krishna while performing converts potentially binding activity into liberating sacrifice, demonstrating consciousness-quality trumps action-type for determining spiritual effect.",
    
    "bg5-q11": "Karma-yogins perform kayena (with body), manasa (with mind), buddhya (with intelligence), indriyaih (with senses)-all for atma-shuddhaye (self-purification) abandoning attachment. The trap: partial engagement sufficiency. Why this matters: The false path is mechanical external service-performing physical actions without mental/intellectual engagement, producing robotic practice lacking consciousness-transformation. Real understanding: Total engagement required-kayena (physically), manasa (mentally), buddhya (intellectually), indriyaih (through all senses)-comprehensive absorption in service for atma-shuddhaye (purifying self). Not just doing right things externally but thinking/feeling/understanding rightly internally. Sangam tyaktva (abandoning attachment)-surrender of proprietorship not just bodily labor. Therefore engage completely in devotional service-body/mind/intelligence/senses all absorbed in Krishna-consciousness, producing thorough purification more effective than partial mechanical compliance.",
    
    "bg5-q12": "Yukta (engaged one) abandoning karma-phala (work-fruits) obtains shaswat (eternal) shanti (peace); ayukta (unengaged) attached to desires becomes bound by kama (lust). The trap: result-seeking produces success. Why this matters: The false path is outcome-orientation-performing spiritual practice for specific attainments, remaining result-attached though religiously, missing peace comes from surrender not achievement. Real understanding: Yukta giving up fruits obtains naishthiki shanti (eternal peace)-not peace from getting desired results but peace from transcending desire for results. Ayukta pursuing kama-driven results remains bound regardless of success-achieving desires doesn't liberate but chains through attachment. Therefore cultivate result-indifference-perform duties as offering without expectation, finding peace in surrender itself not in attainments produced, inverting material achievement-orientation even within spiritual practice.",
    
    "bg5-q13": "Sarvakarmani (all actions) manasa (mentally) sannyasya (renouncing)-dehi (embodied being) sukham (happily) vashi (controlled) resides in nine-gated city neither doing nor causing. The trap: physical renunciation necessity. Why this matters: The false path is external withdrawal requirement-thinking liberation requires abandoning all action-engagement, missing mental renunciation while externally engaged achieves same result. Real understanding: Manasa sannyasya (mentally renouncing)-internal detachment not external cessation. Dehi (embodied soul) happily self-controlled nava-dvare pure (in nine-gated city-body) neither karman kurvan (doing actions) nor karayan (causing actions)-transcendentally situated though appearing active. Enables grhastha (householder) liberation-full external engagement with internal freedom. Therefore practice mental sannyasa-renounce proprietorship/agency/enjoyment claims while maintaining duty-performance, achieving renunciation's fruit without renunciation's form.",
    
    "bg5-q14": "Na kartrittvam (not agency), na karmani (not actions), na karma-phala-samyogam (not action-fruit-connection)-prabhu (Lord) creates for world; svabhavas (nature) pravartate (acts). The trap: divine responsibility-displacement. Why this matters: The false path is blaming God for one's situation-treating karma as divine imposition rather than self-generated consequence, avoiding responsibility through theological determinism. Real understanding: Prabhu doesn't create kartritvam (agency sense) or karma-phala-yoga (action-result connection) for people-individuals generate these through false ego claiming 'I do, I enjoy results.' Svabhavas tu (nature however) pravartate (acts)-material nature executes while individual claims credit/blame. God neither forces nor prevents-provides facility while individual chooses engagement. Therefore accept responsibility-karma is self-generated through false ego not God-imposed, liberation possible through correcting false claims not demanding divine intervention.",
    
    "bg5-q15": "Vibhu (all-pervading Lord) receives neither papam (sin) nor punyam (piety); jnana (knowledge) covered by ajnana (ignorance)-beings thus deluded. The trap: God judges/rewards/punishes. Why this matters: The false path is anthropomorphic theism-projecting human moral accounting onto Supreme, thinking He tracks sins/merits dispensing rewards/punishments, missing He's beyond material morality-platform. Real understanding: Vibhu (omnipresent) doesn't receive anyone's papa/punya-not keeping moral ledger distributing justice. Individuals suffer/enjoy own karma through material nature's impersonal functioning. Ajnanena (by ignorance) avritam (covered) jnanam (knowledge)-beings deluded by own ignorance not divine punishment. Therefore transcend moral-accounting religiosity-God doesn't reward/punish but witnesses souls experiencing self-generated consequences through nature's mechanism, liberation comes from knowledge-recovery not from earning divine favor through merit-accumulation.",
    
    "bg5-q16": "When jnana (knowledge) destroys ajnana (ignorance), tat jnana (that knowledge) reveals paramam (supreme) like aditya (sun). The trap: intellectual accumulation equals enlightenment. Why this matters: The false path is information-collecting-assuming more data produces realization, missing that removing ignorance-covering reveals pre-existing knowledge. Real understanding: Knowledge doesn't create new understanding but removes covering (ajnanena avritam) obscuring natural vision-like sun doesn't create light but removes clouds revealing already-present sunshine. Revelation not creation-soul's inherent knowing covered by material conditioning, spiritual practice removes covering enabling natural vision. Therefore practice negative epistemology-remove false concepts obscuring truth rather than accumulating information building truth, purification reveals inherent spiritual vision naturally present when material contamination eliminated.",
    
    "bg5-q17": "Tad-buddhi (intelligence fixed in That), tad-atma (self absorbed in That), tad-nishtha (established in That), tat-parayana (ultimate goal being That)-go without return. The trap: divided spiritual attention. Why this matters: The false path is compartmentalized practice-being spiritual in temple, material in marketplace-missing total absorption requirement for liberation. Real understanding: Four-fold absorption-buddhi (intelligence thinking about Krishna), atma (identity as Krishna's), nishtha (constant establishment in Krishna), parayana (ultimate goal being Krishna). Comprehensive totality-not partial Krishna-orientation but total life-reorganization around Supreme. Apunar-avritti (no return)-such complete absorption prevents rebirth because material interest fully displaced. Therefore cultivate total absorption-not segmented spirituality (religious occasions only) but comprehensive life-reorientation where Krishna becomes center of intelligence/identity/stability/goals, producing thoroughgoing transformation preventing material backslide.",
    
    "bg5-q18": "Panditah (wise) sama-darshina (equipoised vision) toward brahmana endowed with knowledge/humility, cow, elephant, dog, chandala-sees self in all. The trap: social equality misconstrued as material equality. Why this matters: The false path is either rejecting all distinctions (radical egalitarianism) or maintaining oppressive distinctions (casteism)-missing transcendental vision honors soul-equality while recognizing bodily diversity's practical reality. Real understanding: Sama-darshina sees atma (self) equally in brahmana and chandala, cow and elephant-spiritual vision transcending bodily varieties. Doesn't mean ignoring functional differences-brahmana receives respect for knowledge, chandala performs appropriate service, but spiritual vision sees equal soul beyond unequal bodies. Therefore develop sama-drishti-recognize soul's equal value regardless of bodily designation, preventing both arrogant superiority and false material equality-claims, maintaining functional social distinctions while transcending them spiritually.",
    
    "bg5-q19": "Same-sighted (samena) conquer birth-death cycle here; Brahman flawless (nirdosham) and sama (equal)-established in Brahman. The trap: after-death liberation only. Why this matters: The false path is postponing liberation to post-mortem realm-thinking freedom comes only after death, missing that present Brahman-consciousness liberates now. Real understanding: Ihaiva (here itself) jitah sarga (conquered birth-death)-present realization conquers material conditioning currently not eventually. Brahman nirdosham (flawless) and samam (equal)-present Brahman-realization now, not future attainment later. Liberation isn't post-mortem reward but present state-consciousness shift from material to spiritual accomplished now. Therefore don't postpone liberation-cultivate present Brahman-consciousness achieving freedom from birth-death cycle's psychological grip immediately, transformation occurring now through consciousness-shift not awaiting future death for freedom.",
    
    "bg5-q20": "Neither rejoicing upon pleasant (priyam) nor disturbed by unpleasant (apriyam)-sthira-buddhir (steady intelligence), asammudhah (unbewildered), brahma-vid (knower of Brahman) sthitah (situated) in Brahman. The trap: emotional suppression demonstrates realization. Why this matters: The false path is forced neutrality-mechanically flattening all responses through willpower, producing artificial equanimity brittle under stress. Real understanding: Natural equanimity from Brahman-realization-priyam/apriyam don't disturb sthira-buddhi (steady intelligence) not from suppression but from Brahman-absorption providing satisfaction transcending material dualities' push-pull. Asammudhah (unbewildered)-clarity about what matters makes material fluctuations irrelevant. Therefore seek natural not forced equanimity-Brahman-connection generates satisfaction making dualities non-threatening naturally, achieving steady-consciousness through spiritual absorption not through emotional suppression requiring constant maintenance.",
    
    "bg5-q21": "Bahya-sparseshu (in external contacts) asaktam (unattached)-finds sukham (happiness) atmani (in self); brahma-yoga-yukta-atma (self engaged in Brahman-yoga)-obtains akshayam (inexhaustible) sukham (happiness). The trap: external stimulation provides satisfaction. Why this matters: The false path is pursuing happiness through sense-contact multiplication-assuming more/better external experiences produce fulfillment, generating perpetual dissatisfaction requiring escalating stimulation. Real understanding: Asaktam external contacts-finds happiness atmani (internally) not bahya-sparseshu (in external touches). Brahma-yoga-yukta (engaged in Brahman-yoga)-obtains akshayam (inexhaustible) happiness not ksayam (perishable) happiness from material contact. Inverts hedonism-satisfaction from within makes external contacts irrelevant for happiness. Therefore cultivate internal spiritual connection-brahma-yoga generates inexhaustible happiness independent of external circumstances, freeing from perpetual external-stimulus-seeking producing anxiety and incompleteness endemic to materially-oriented life.",
    
    "bg5-q22": "Sense-contact pleasures (bhoga) are duhkha-yonaya (womb of misery); have adi-anta (beginning-end)-wise don't rejoice in them. The trap: pleasure pursued produces happiness. Why this matters: The false path is hedonistic happiness-pursuit-maximizing pleasure-experiences expecting fulfillment, missing that sense-pleasure inherently produces duhkha (misery) not sukha (happiness). Real understanding: Ye hi samsparshaja (those born of sense-contact) bhogah (pleasures) duhkha-yonayah (wombs of misery)-pleasure itself contains pain's seed. Adi-anta-vantah (having beginning-end)-temporality guarantees dissatisfaction through anticipation-anxiety and loss-grief. Buddhiman (intelligent) therefore na ramate (doesn't rejoice) in such pleasures-not masochism but discrimination recognizing temporary pleasures' hidden cost. Therefore transcend hedonic treadmill-sense-pleasure inherently unsatisfying due to temporality, seek permanent satisfaction through transcendental engagement rather than chasing intrinsically frustrating material pleasures escalating in intensity.",
    
    "bg5-q23": "Who can resist kama-krodha (lust-anger) vegam (impulse) before deha-vimokshana (body-liberation)-yukta (engaged), sukhi (happy) narah (person). The trap: after-death-only liberation. Why this matters: The false path is postponing victory over lust/anger to death-assuming current life remains battleground with freedom only posthumously, missing present victory possibility. Real understanding: Prak sharira-vimokshanat (before body-liberation)-during current embodiment, sodhum (tolerate) kama-krodha vegam (lust-anger impulse)-achieve victory now not later. Sa yuktah (he is engaged) sa sukhi (he is happy) narah (person)-present attainment not future hope. Therefore don't postpone self-mastery-can conquer material impulses currently through spiritual practice, liberation from kama-krodha's tyranny achievable now producing present happiness rather than deferred to speculative after-death state.",
    
    "bg5-q24": "Antah-sukha (inner joy), antar-arama (inner satisfaction), antar-jyoti (inner illumination)-such yogi attains brahma-nirvanam (Brahman-liberation). The trap: external achievement demonstrates spiritual success. Why this matters: The false path is external-result spirituality-measuring advancement through material accomplishments or public recognition, missing internal realization defines genuine success. Real understanding: Three-fold interiority-sukha (joy) antah (within), arama (satisfaction) antah (within), jyoti (light) antah (within). Not external validation but internal realization-happiness/satisfaction/illumination sourced internally not externally. Such yogi brahma-nirvanam (Brahman-liberation)-achieves freedom through internal transformation not external attainment. Therefore cultivate internal measures-spiritual advancement gauged by inner peace/satisfaction/clarity, not external accomplishments/recognition, inverting material success-metrics even within spiritual practice.",
    
    "bg5-q25": "Rishis (sages) kshin-kalmashah (destroyed sins), chinna-dvaidha (cut dualities), yata-atmanah (self-controlled), sarva-bhuta-hite-ratah (engaged in all beings' welfare)-obtain brahma-nirvanam (Brahman-liberation). The trap: self-focused spirituality. Why this matters: The false path is privatized practice-pursuing personal liberation without concern for others' welfare, missing genuine realization produces compassionate welfare-work. Real understanding: Final qualification sarva-bhuta-hite-ratah (engaged in welfare of all beings)-genuine spiritual advancement produces universal compassion, not selfish isolation. After kshin-kalmasha (sin-destruction), chinna-dvaidha (duality-transcendence), yata-atmanah (self-control)-naturally works for collective welfare. Liberation includes compassion-personal freedom incomplete without welfare-orientation toward all beings. Therefore authentic spiritual progress manifests outwardly-not just internal purification but external welfare-engagement, demonstrating liberation through compassionate service rather than isolated perfection."
}

print("\n=== Chapter 5 Enhancement ===")
q5 = enhance_chapter(5, ch5_enhancements)

print(f"\n✅ SUMMARY: Ch4 quality={q4:.0f}%, Ch5 quality={q5:.0f}%")
print("All enhancements complete with trap -> false path -> real understanding pattern")
