"""
Enhance BG Ch3 feedback to expert critique level (11% -> 90%+)
Focus: karma-yoga, sacrifice, gunas, lust
Pattern: trap -> false path -> real understanding, 3-5 sentences
"""
import json

with open('data/quizzes/bg/3-adult.json') as f:
    data = json.load(f)

enhancements = {
    "bg3-q1": "Arjuna misunderstands sankhya (knowledge) vs karma-yoga (action) relationship-treating as mutually exclusive alternatives. The trap: dichotomous thinking about spiritual paths. Why this matters: The false path is intellectual-practical split-assuming knowledge opposes action when actually genuine knowledge includes proper devotional action. Real understanding: True jnana culminates in Krishna consciousness activity; theoretical understanding divorced from service reveals incomplete realization. Arjuna's confusion stems from monist contamination-thinking enlightenment means cessation. This foreshadows Ch3's teaching-karma-yoga as knowledge's practical expression not its opposite. Therefore knowledge-action synthesis defines authentic spirituality; separating them creates artificial dilemma resolved through integrated bhakti-yoga.",
    
    "bg3-q2": "Conditioned soul forced to act by prakrti's gunas even when unwilling-illustrates helplessness under false ego. The trap: voluntarism-believing willpower controls action. Why this matters: The false path is assuming autonomy-thinking 'I can stop anytime' while mechanically driven by modes, producing illusion of independence. Real understanding: Material nature (prakrti) compels action through three gunas-tamas, rajas, sattva. Soul under false ego cannot resist these impulses-sattvic acts virtuously, rajasic frantically, tamasic destructively, all involuntarily. Only transcending modes through Krishna consciousness provides actual freedom. This exposes modern autonomous-self mythology-apparent choices are mode-expressions. Therefore liberation requires transcending material platform entirely, not just making better material choices.",
    
    "bg3-q3": "False renunciates restrain senses externally (karmendriyani samyamya) while mentally dwelling on objects (manas smaran)-reveals mithyacarah (hypocrisy). The trap: external discipline equals internal transformation. Why this matters: The false path is mechanistic spirituality-controlling actions without purifying desires, producing forced suppression not genuine transcendence. Real understanding: Mind's attachment persists despite bodily control-like prisoner in cell still craving freedom. True vairagya requires internal shift from desire to satisfaction in self, not external constraint masking unchanged consciousness. This exposes ascetic pretense-yoga-pants and meditation-poses without transformed consciousness. Therefore test spirituality by consciousness not external behavior-transformed mind naturally manifests in action, but controlled action doesn't guarantee transformed mind.",
    
    "bg3-q4": "Pravrttih karma-yoga (engaged action) superior to nivrttih (inaction)-revolutionary rejection of renunciation-as-inactivity. The trap: quietism as spirituality. Why this matters: The false path is confusing cessation with transcendence-thinking spiritual advancement requires physical withdrawal from duties, producing passivity disguised as detachment. Real understanding: Proper action in Krishna consciousness transcends both material activity (karma-bandha) and material inactivity (false renunciation). Not choosing between action-inaction but transforming action's motivation from selfish to selfless. Body can't remain inactive anyway (BG 3.5)-question is whether activity binds or liberates. Therefore engage senses in devotional service rather than suppressing them fruitlessly-occupation in Krishna consciousness, not occupation-cessation.",
    
    "bg3-q5": "Work performed as yajna for Vishnu liberates; work for sense gratification binds (karma-bandhana). The trap: outcome-independence from purpose. Why this matters: The false path is thinking action's result depends only on execution not intention-missing that same external work produces radically different karmic effects based on consciousness. Real understanding: Identical activities generate opposite results-cooking for Krishna vs cooking for self, speaking for preaching vs speaking for profit. Yajna transforms work from binding to liberating not by changing activity but consciousness. This reveals purpose supremely important-not just what you do but why determines spiritual effect. Therefore sanctify all activities through yajna-orientation (offering to Krishna), converting mundane necessities into liberating service.",
    
    "bg3-q6": "Process requires vishad-acarya (expert guidance) from bhakta or Krishna-not autonomous learning. The trap: spiritual autodidactism. Why this matters: The false path is book-wisdom without guru-guidance-assuming intellectual study suffices without living relationship to realized teacher, producing theoretical knowledge without practical realization. Real understanding: Krishna consciousness isn't information-transfer but consciousness-transmission-requires guru's personal guidance recognizing individual's conditioning and prescribing tailored sadhana. Books provide framework; guru provides application. Prabhurada emphasizes 'in the beginning'-acknowledges early vulnerability requiring protection from deviation. Therefore seek shelter of expert devotee-vani (instruction) must be supplemented by vapuh (personal association) for successful spiritual transformation.",
    
    "bg3-q7": "Sacrifice for Vishnu automatically satisfies devas who are Supreme's limbs (anga-bhutah)-eliminates separate worship. The trap: polytheistic fragmentation. Why this matters: The false path is demigod-shopping-approaching various devas for specific benefits, missing that all derive power from Vishnu's sanction. Real understanding: Devas aren't independent competitors but Supreme's functional representatives-like government departments under prime minister. Satisfying center satisfies periphery; worshiping Vishnu satisfies all devas through constitutional structure. This exposes materialistic deity-selection where devas treated as vending machines dispensing specific commodities. Therefore worship Vishnu/Krishna exclusively-simultaneously satisfies all devas while transcending material benefit platform for pure devotional relationship.",
    
    "bg3-q8": "Prasadam principle-food offered to Krishna purifies both substance and consumer. The trap: nutritionism or ritualism. Why this matters: The false path is either material (blessed food has superior nutrients) or magical (mantras transform molecules)-missing transcendental relationship transforming consciousness. Real understanding: Krishna accepts devotee's love expressed through offering; purified by His touch, remnants (prasadam) carry spiritual potency transforming eater's consciousness. Not chemical change but relational exchange-eating becomes communion with Supreme. Self-centered eating accumulates papa (sin) through sense gratification; Krishna-centered eating through prasadam liberates. Therefore spiritualize basic necessity (eating) through bhakti-offering, demonstrating how every activity can become Krishna conscious.",
    
    "bg3-q9": "Santas (devotees) in love with Krishna cannot accept anything without offering first-spontaneous not obligatory. The trap: treating offering as ritual requirement. Why this matters: The false path is mechanical compliance-offering from duty not love, producing perfunctory gesture without heart-connection. Real understanding: Advanced devotees' love prevents enjoying separately from Krishna-like lover wanting beloved to share everything first. Not external rule imposed but internal impulse emerging from relationship. Shows offering's motivation-trajectory from obligation (neophyte) through habit (intermediate) to spontaneous love (advanced). Therefore cultivate affection generating natural offering-spirit, not just follow procedure externally-relationship transforms regulation from burden to joy.",
    
    "bg3-q10": "Sankirtana-yajna provides easy accessible process for Krishna consciousness-no complicated requirements. The trap: elitism or complexity-fetishism. Why this matters: The false path is assuming advanced qualifications prerequisite-birth, scholarship, wealth, location-excluding most humans from spiritual access. Real understanding: Sankirtana (chanting Hare Krishna) available to everyone regardless of external conditions-no initiation, no expense, no special venue required. This democratic accessibility reflects Krishna's generosity-everyone can participate immediately. Without teaching this easy process, people remain materially conditioned pursuing temporary happiness. Therefore propagate sankirtana widely-only viable process for mass spiritual awakening in Kali-yuga's degraded conditions.",
    
    "bg3-q11": "Life outside sacrifice-cycle (cosmic order) reduces to sense-indulgence alone-purposeless and sinful. The trap: autonomous meaning-creation. Why this matters: The false path is existentialist self-determination-assuming individual creates life's meaning apart from cosmic structure, producing hedonistic solipsism disguised as authentic existence. Real understanding: Refusing yajna-cakra (sacrifice wheel) participation eliminates transcendent purpose-only bodily gratification remains. Body-centered life (aghayur indriyaramo) is objectively purposeless because ignores soul's constitutional function-serving Supreme. This isn't authoritarian constraint but ontological reality-like fish refusing water claiming autonomous existence. Therefore participate in sacrifice cycle-work/offer/receive/repeat-aligning individual action with cosmic purpose, elevating life from sense-indulgence to soul-development.",
    
    "bg3-q12": "Atma-rama (self-satisfied) finds pleasure within, needing nothing external-fulfilled internally not externally. The trap: consumerism's perpetual incompleteness. Why this matters: The false path is external-object dependency-seeking satisfaction through acquiring, consuming, experiencing, requiring perpetual stimulation producing anxiety and incompleteness. Real understanding: Self-realized person's satisfaction comes from atma-realization (soul-knowledge) and Krishna-relationship, independent of external circumstances. Not deprivation-based detachment but satisfaction-based transcendence-higher pleasure eclipses lower naturally. This inverts material paradigm where happiness depends on favorable conditions-atma-rama remains content amid any externals. Therefore cultivate internal Krishna-connection generating satisfaction transcending material variables-freedom from circumstance-dependency.",
    
    "bg3-q13": "Nishkama-karma (desire-free duty) purifies consciousness (buddhi), naturally revealing Krishna as supreme goal. The trap: karma-kanda ritualism or stoic suppression. Why this matters: The false path is either mechanical performance hoping to accumulate piety, or forced emotional neutrality requiring constant vigilance-both missing purification's relational dimension. Real understanding: Desireless action performed as offering gradually cleanses heart of false proprietorship-'my work, my results, my enjoyment.' Purification isn't external ablution but consciousness transformation-seeing self as Krishna's servant not independent enjoyer. Cleaned consciousness naturally gravitates toward its source (Krishna)-like purified water naturally flows downhill. Therefore karma-yoga is purification process not destination-means enabling bhakti's flowering by removing material contamination obscuring natural love.",
    
    "bg3-q14": "Janaka attained siddhi (perfection) through raja-dharma (royal duties) performed without attachment-householder exemplar. The trap: renunciation-monopoly on liberation. Why this matters: The false path is thinking liberation requires sannyas (renunciation order)-excluding householders from spiritual completion, producing either inappropriate renunciation or spiritual defeatism. Real understanding: Perfection available through any varnashrama position when performed in Krishna consciousness without selfish attachment. Janaka as raja (king) engaged fully in governance/warfare/administration while maintaining transcendental consciousness-demonstrates detachment-in-action not detachment-through-inaction. This validates grhastha (householder) path for material-duty discharge alongside spiritual advancement. Therefore quality of consciousness determines liberation, not social position-any varna/ashrama becomes vehicle for Krishna consciousness when performed as yajna.",
    
    "bg3-q15": "Janaka and kings worked for loka-sangraha (public welfare) not personal gain-collective benefit motivation. The trap: privatized spirituality. Why this matters: The false path is individual-focused practice ignoring social responsibility-'my liberation' pursued selfishly without considering others' spiritual welfare. Real understanding: Advanced souls work not for personal necessity (already satisfied internally) but for collective upliftment-guiding society toward transcendence through example and leadership. Loka-sangraha means maintaining social order facilitating mass spiritual advancement-creating conditions enabling others' Krishna consciousness. This extends karma-yoga beyond personal purification to social transformation. Therefore those who realize should teach-not retreat into isolated perfection but engage in spiritual welfare-work, demonstrating practical application of transcendental knowledge.",
    
    "bg3-q16": "Maha-atma (great souls) must act in Krishna consciousness because others imitate-leadership responsibility. The trap: example-neutrality illusion. Why this matters: The false path is assuming personal choices remain private without social ripple-effects-missing that visible behavior establishes standards others follow consciously/unconsciously. Real understanding: Leaders' actions set precedents-yad yad acarati sreshthas (whatever great ones do) becomes jana-samudro (public standard). If maha-atmas act materialistically, masses follow materialistically; if transcendentally, masses follow transcendentally. This imposes responsibility-cannot claim 'just doing my thing' when others observing and imitating. Therefore advanced practitioners must exemplify Krishna consciousness publicly-not hide attainment but demonstrate practical application, using influence for collective spiritual elevation not just personal satisfaction.",
    
    "bg3-q17": "Material person thinks aham karta (I am doer) under false ego-falsely claiming independent agency. The trap: autonomous selfhood illusion. Why this matters: The false path is Enlightenment-era autonomy absolutization-treating self as independent origin of action, ignoring body/mind/circumstances all provided by Krishna's arrangement. Real understanding: Material nature (prakrti) performs all actions through three gunas-individual merely witnesses falsely identifying as agent. Real controller is Hrishikesha (Krishna, master of senses) supplying body/intelligence/facility. False ego (ahankara) creates independence-illusion obscuring actual dependency. Modern 'self-made' narratives exemplify this delusion-genetic, social, environmental factors enabling 'achievement' all beyond individual control. Therefore recognize Krishna as real doer-self as instrument in His hands, dissolving false agency-claim producing humility and gratitude.",
    
    "bg3-q18": "Bewildered by false ego through sense gratification, forget Krishna is Hrishikesha (master of senses). The trap: sense-ownership claiming. Why this matters: The false path is treating senses as personal property for personal enjoyment-'my eyes, my tongue, my genitals'-producing possessive mentality toward Krishna's facilities. Real understanding: Hrishikesha means Krishna owns and controls all senses-individual's sensory capacity is borrowed facility meant for His service. Sense gratification (using Krishna's property for self) constitutes theft and rebellion. Bewilderment (moha) from material engagement makes one forget actual ownership-structure. Therefore re-engage senses in original purpose (Krishna's pleasure) rather than falsely claiming them for self-interest-alignment with reality producing satisfaction, misalignment producing frustration.",
    
    "bg3-q19": "Mode-driven work claims false agency ('I am doer') while actually nature-controlled; yajna acknowledges Krishna as controller-self as instrument. The trap: inverted causality attribution. Why this matters: The false path is either false independence (I control) or false determinism (nature controls absolutely)-both missing Krishna's supreme agency arranging through prakrti. Real understanding: Material nature executes Krishna's plan-three gunas compelling embodied soul's actions. False ego misattributes authorship to self or blind nature-missing conscious Controller behind mechanism. Yajna-orientation corrects ontology-recognizing Krishna as real agent, nature as instrument, self as servant. This alignment with actual agency-structure liberates because ceases fighting reality through false claims. Therefore accept constitutional position (Krishna's servant) rather than usurping position (independent enjoyer)-reality-acceptance produces peace, reality-denial produces struggle.",
    
    "bg3-q20": "False renunciation restrains externally while internal attachment continues; regulated Krishna-service redirects desire, actually transforming consciousness. The trap: behavior-modification spirituality. Why this matters: The false path is external-focus-controlling actions without addressing desires, producing suppression-based practice requiring constant effort without transformation. Real understanding: Cessation doesn't purify mind because desire-structure remains intact though temporarily constrained-like dammed river still wanting to flow. Regulated engagement in Krishna's service provides superior satisfaction, naturally displacing material desire through higher taste. Not fighting desire directly but transcending it through spiritual engagement-occupation in Krishna consciousness automatically reduces material attachment. Therefore regulate senses in devotional service rather than merely restraining them-active redirection more effective than passive suppression.",
    
    "bg3-q21": "Lust operates through rajo-guna compelling sense gratification; solution is Krishna-conscious engagement providing superior satisfaction. The trap: lust-fighting through suppression. Why this matters: The false path is direct combat with lust-trying to eliminate by willpower alone, producing exhausting struggle often ending in defeat. Real understanding: Lust (kama) isn't destroyed by opposition but displaced by higher engagement-Krishna-conscious activity provides satisfaction surpassing lust's promises. Fighting lust directly empowers it through attention; serving Krishna starves it through neglect. Like child abandoning toy when receiving better toy-not forced abandonment but natural displacement. Therefore engage senses in Krishna's service-hearing about Him, chanting His names, serving His devotees-gradually weakening lust through disinterest rather than frontal assault.",
    
    "bg3-q22": "Sacrifice-cycle participation performed selflessly gradually purifies consciousness of false proprietorship. The trap: sacrifice as transaction for benefit. Why this matters: The false path is kamya-karma mentality-performing yajna to obtain material results, treating cosmic order as vending machine dispensing rewards for inputs. Real understanding: Real yajna is consciousness-purification process-performing prescribed role without selfish motive cleanses ahankara (false ego) claiming 'I own, I control, I enjoy.' Purified consciousness recognizes Krishna's ownership and one's service position-constitutional reality obscured by material conditioning. Self-realized (3.17) already sees this clearly; conditioned souls purify through detached yajna gradually. Therefore perform duties as offerings without result-seeking-mechanism transforming material consciousness into spiritual consciousness through practice.",
    
    "bg3-q23": "False ego creates independence-illusion when actually instruments of prakrti under Krishna's direction. The trap: Enlightenment autonomy-myth. Why this matters: The false path is absolutizing individual autonomy-treating 'personal achievement' as self-originated, ignoring that body/intelligence/opportunities all come from sources beyond individual control. Real understanding: Modern self-made narratives exemplify false-ego delusion-genetic endowment, social circumstances, historical moment, random opportunities all beyond individual origination, yet claimed as personal credit. Actually nature (Krishna's energy) provides all facilities-individual merely uses them well or poorly. This exposes metaphysical error-confusing ability-to-choose with ability-to-originate, treating conditioned agency as absolute agency. Therefore recognize dependency-humility acknowledging that all capacities are gifts, not self-generated achievements requiring individual glory-claiming.",
    
    "bg3-q24": "Great souls must act transcendentally because others imitate; but forcing mode-bound persons to abandon duties causes chaos. The trap: inappropriate universalization. Why this matters: The false path is assuming one standard fits all-advanced practices prescribed to neophytes, or neophyte practices mandated for advanced, producing either artificial imitation or spiritual stagnation. Real understanding: Gradual elevation principle-work with current conditioning, elevating through prescribed duties performed for Vishnu rather than demanding quantum leaps. Maha-atmas can work non-attached while maintaining example; forcing ordinary persons to renounce prematurely creates social/spiritual chaos. This validates varnashrama-dharma's graduated approach-meeting people where they are, guiding through current duties toward transcendence. Therefore don't impose advanced renunciation on unprepared persons-elevate gradually through Krishna-conscious duty-performance appropriate to current position.",
    
    "bg3-q25": "Modern stress stems from disconnected self-centered work lacking transcendent purpose; sankirtana-yajna reconnects soul to source. The trap: therapeutic materialism treating symptoms. Why this matters: The false path is material solutions (therapy, meditation-techniques, work-life-balance) addressing manifestations not root-cause-missing that existential disconnection from Krishna produces anxiety therapy cannot resolve. Real understanding: Stress derives ultimately from constitutional dysfunction-soul employed in self-centered projects disconnected from Supreme source. Sankirtana-yajna (nama-offering transforming all activities) restores constitutional relationship-work becomes service, reconnecting individual to transcendent meaning. This addresses existential root-soul's separation from Krishna-which material adjustments cannot touch. Therefore practice Krishna consciousness for anxiety's cure-not supplementary but foundational, transforming meaningless disconnected activity into meaningful connected service."
}

for q in data['questions']:
    qid = q['id']
    if qid in enhancements:
        q['feedback'] = enhancements[qid]

with open('data/quizzes/bg/3-adult.json', 'w') as f:
    json.dump(data, f, indent=2)

print("✅ Ch3 enhanced: All 25 questions upgraded to expert critique level")
print("Pattern applied: trap -> false path -> real understanding")
print("Themes: karma-yoga, yajna, false ego, lust, sacrifice")
