import fs from "fs";
import path from "path";
import satori from "satori";
import { Resvg } from "@resvg/resvg-js";

async function generate() {
  const title = "Sample: Bhagavad Gita";
  const score = 0;
  const total = 20;
  const emoji = "✨";

  const cacheDir = path.join(process.cwd(), "og_cache");
  if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir, { recursive: true });
  const outPath = path.join(cacheDir, `sample.png`);

  // try to load font
  let fonts = [];
  try {
    const fontPath = path.join(process.cwd(), "public", "fonts", "Vedabase-Regular.ttf");
    if (fs.existsSync(fontPath)) {
      const fontData = fs.readFileSync(fontPath);
      fonts.push({ name: "Vedabase", data: fontData, weight: 400, style: "normal" });
      console.log("Loaded Vedabase font for satori");
    } else {
      console.log("Vedabase font not found; using system fallback");
    }
  } catch (e) {
    console.warn("Font load failed:", e.message);
  }

  const svg = await satori(
    (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          width: 1200,
          height: 630,
          background: "linear-gradient(180deg,#ffffff,#f5f7ff)",
          fontFamily: fonts.length ? "Vedabase, Arial, sans-serif" : "Arial, sans-serif",
          padding: 48,
        }}
      >
        <div style={{ color: "#d4a574", fontSize: 20, fontWeight: 700 }}>VEDABASE QUIZ</div>
        <div style={{ fontSize: 48, fontWeight: 800, color: "#1e3a8a", marginTop: 18 }}>Certificate of Achievement</div>
        <div style={{ fontSize: 28, color: "#6b5d47", marginTop: 16 }}>{title}</div>

        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 24,
            marginTop: 34,
          }}
        >
          <div style={{ fontSize: 96, fontWeight: 900, color: "#0099ff" }}>{Math.round((score / total) * 100)}%</div>
          <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-start" }}>
            <div style={{ fontSize: 28, color: "#444", fontWeight: 700 }}>{score}/{total} correct</div>
            <div style={{ fontSize: 22, color: "#777", marginTop: 6 }}>{emoji} Well done</div>
          </div>
        </div>

        <div style={{ position: "absolute", right: 48, bottom: 24, fontSize: 14, color: "#999" }}>
          Generated by Vedabase Quiz
        </div>
      </div>
    ),
    {
      width: 1200,
      height: 630,
      fonts,
    }
  );

  const resvg = new Resvg(svg, { fitTo: { mode: "width", value: 1200 } });
  const pngData = resvg.render();
  const pngBuffer = pngData.asPng();

  fs.writeFileSync(outPath, pngBuffer);
  console.log("Wrote sample OG to", outPath);
}

generate().catch((e) => {
  console.error(e);
  process.exit(1);
});
