import satori from "satori";
import { Resvg } from "@resvg/resvg-js";
import fs from "fs";
import path from "path";

// Server route to return PNG OG image for a quiz score
// Example: /api/og?title=Bhagavad%20Gita&score=19&total=20&emoji=%F0%9F%8C%B8
export async function GET(req) {
  try {
    const url = new URL(req.url);
    const title = url.searchParams.get("title") || "Vedabase Quiz";
    const score = Number(url.searchParams.get("score") || "0");
    const total = Number(url.searchParams.get("total") || "0");
    const emoji = url.searchParams.get("emoji") || "✨";
    const pct = total > 0 ? Math.round((score / total) * 100) : 0;

    // Simple filesystem cache to avoid regenerating often
    const cacheDir = path.join(process.cwd(), "og_cache");
    if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir, { recursive: true });

    const key = encodeURIComponent(`${title}|${score}|${total}|${emoji}`);
    const outPath = path.join(cacheDir, `${key}.png`);

    if (fs.existsSync(outPath)) {
      const data = fs.readFileSync(outPath);
      return new Response(data, {
        status: 200,
        headers: { "Content-Type": "image/png", "Cache-Control": "public, max-age=3600" },
      });
    }

    // Attempt to load a custom font from public/fonts/Vedabase-Regular.ttf
    let fontsOption = [];
    try {
      const fontPath = path.join(process.cwd(), "public", "fonts", "Vedabase-Regular.ttf");
      if (fs.existsSync(fontPath)) {
        const fontData = fs.readFileSync(fontPath);
        fontsOption.push({ name: "Vedabase", data: fontData, weight: 400, style: "normal" });
      }
    } catch (e) {
      // ignore font loading errors
    }

    // Simple React-like layout for satori
    const svg = await satori(
      (
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            width: 1200,
            height: 630,
            background: "linear-gradient(180deg,#ffffff,#f5f7ff)",
            fontFamily: fontsOption.length ? "Vedabase, Arial, sans-serif" : "Arial, sans-serif",
            padding: 48,
          }}
        >
          <div style={{ color: "#d4a574", fontSize: 20, fontWeight: 700 }}>VEDABASE QUIZ</div>
          <div style={{ fontSize: 48, fontWeight: 800, color: "#1e3a8a", marginTop: 18 }}>Certificate of Achievement</div>
          <div style={{ fontSize: 28, color: "#6b5d47", marginTop: 16 }}>{title}</div>

          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 24,
              marginTop: 34,
            }}
          >
            <div style={{ fontSize: 96, fontWeight: 900, color: pct === 100 ? "#2f7d32" : "#0099ff" }}>{pct}%</div>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-start" }}>
              <div style={{ fontSize: 28, color: "#444", fontWeight: 700 }}>{score}/{total} correct</div>
              <div style={{ fontSize: 22, color: "#777", marginTop: 6 }}>{emoji} {pct === 100 ? 'Perfect score!' : pct >= 90 ? 'Excellent' : 'Well done'}</div>
            </div>
          </div>

          <div style={{ position: "absolute", right: 48, bottom: 24, fontSize: 14, color: "#999" }}>
            Generated by Vedabase Quiz
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
        fonts: fontsOption,
      }
    );

    // Convert SVG -> PNG using resvg
    const resvg = new Resvg(svg, {
      fitTo: { mode: "width", value: 1200 },
    });

    const pngData = resvg.render();
    const pngBuffer = pngData.asPng();

    // Save cache file (best-effort)
    try {
      fs.writeFileSync(outPath, pngBuffer);
    } catch (e) {
      // ignore write errors
    }

    return new Response(pngBuffer, {
      status: 200,
      headers: {
        "Content-Type": "image/png",
        "Cache-Control": "public, max-age=3600, stale-while-revalidate=86400",
      },
    });
  } catch (err) {
    console.error(err);
    return new Response("Error generating image", { status: 500 });
  }
}
